theme: jekyll-theme-cayman
title: Res Latinae Blog
url: https://danelh.github.io
purl: https://danelh.github.io/
pburl: https://danelh.github.io/latin_blog
google_analytics: UA-170550843-1

plugins:
  - jekyll-seo-tag
