theme: jekyll-theme-cayman
title: Res Latinae Blog
url: https://danelh.github.io/latin_blog
baseurl: /latin_blog
purl: https://danelh.github.io/
google_analytics: UA-170550843-1

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
